# Generated by Django 3.1.5 on 2021-02-02 13:23

import app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_auto_20210130_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(default=None, upload_to='media/', validators=[app.models.Photo.validate_image_size, app.models.Photo.validate_image_format], verbose_name='Фотография'),
        ),
        migrations.AlterUniqueTogether(
            name='photo',
            unique_together={('name', 'user')},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
