# Generated by Django 3.1.5 on 2021-02-02 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210202_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='foto_resize',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='public',
        ),
    ]
