# Generated by Django 3.1.6 on 2021-02-02 21:03

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210202_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='foto',
            field=models.ImageField(default=None, upload_to='', validators=[app.models.Photo.validate_image_size, app.models.Photo.validate_image_format], verbose_name='Фотография'),
        ),
    ]
