# Generated by Django 3.1.6 on 2021-02-02 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210202_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='foto',
            new_name='img',
        ),
    ]
